version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.34
    - 14.14.35
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: next
    versions:
    - 10.0.9
    - 10.1.1
    - 10.1.2
    - 10.1.3
  - dependency-name: next-i18next
    versions:
    - 8.1.1
    - 8.1.2
    - 8.1.3
  - dependency-name: preact-render-to-string
    versions:
    - 5.1.15
    - 5.1.16
    - 5.1.17
    - 5.1.18
  - dependency-name: faunadb
    versions:
    - 4.1.2
    - 4.1.3
  - dependency-name: "@hcaptcha/react-hcaptcha"
    versions:
    - 0.3.5
